### PR TITLE
fix(ResizeMonitor) don't monitor null elements

### LINKED ISSUE #101: Uncaught TypeError: Cannot read property 'clientWidth' of null at monitor.js
A component in state "destroying" is added to monitoring at https://github.com/html-next/flexi/blob/master/addon/mixins/container.js#L45 

It has element = null, which leads to the issue later on. Because null.clientwidth is expected to exist here: https://github.com/html-next/flexi/blob/master/addon/lib/monitor.js#L75

screenshot

### PR DESCRIPTION
**Pull request by kybishop**
Fixes #101 

@RobIsHere thought you might want to take a look before I pass this on to someone for review.

### CODE REVIEW

**Comment by RobIsHere** [comment]
I copy+pasted this change to my installation and it worked.

**Comment by kybishop** [comment]
@rwwagner90 passing this your way since I know you're working on splitting out the elements of Flexi.

**Comment by kybishop** [comment]
Reverting this to a WIP until we have more feedback. I'm scratching my head as to how a component can be in the `isDestroying`/`isDestroyed` state before `didInsertElement` is called. @RobIsHere would love steps to reproduce before moving forward

**Comment by kybishop** [comment]
More info: https://github.com/html-next/flexi/issues/101#issuecomment-269933792

Ready for review

**Comment by kybishop** [comment]
Closing this in favor of a different approach, will open a new pull request soon.

**Pull request closed without merging**
