### PR TITLE
[WIP] Fix Documentation Site

### PR DESCRIPTION
**Pull request by runspired**
Mostly this entails waiting until liquid-fire has a branch / release that works with both Glimmer2 (the glimmer2 branch does) and older Ember.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@runspired should we care if the docs site works with older Ember?

**Comment by runspired** [comment]
@rwwagner90 yes, because it breaks our tests if it doesn't :troll:

**Comment by runspired** [comment]
(hence this not being merged)

**Comment by rwwagner90** [comment]
@runspired I didn't think about the docs site being what tests ran against. Never mind 😛

**Comment by kybishop** [comment]
closing this in favor of the new docs site

**Pull request closed without merging**
