### PR TITLE
Feature: Fullscreen layout example

### PR DESCRIPTION
**Pull request by xtagon**
@rwwagner90 I did my best to add the example layout you asked for. It took some tweaking to get it to actually work, and the implementation is not pretty.

It works and looks as expected in Chrome and Firefox in my testing, but:

- There is no SVG, I just copied one of the existing ones
- I had to add some CSS rules to `html`, `body`, and the root ember view. Feels dirty but it was the only way to get fullscreen to work.
- I couldn't get it to work in a component (even with your tip about using dash in the component name) probably because doing so introduces an ember-view div that doesn't have the `fullscreen` class.
- I couldn't get it to work with `liquid-outlet` probably for the same reason, so I ended up doing some muckery with the route by setting a property to bypass both the `<screen>` and `liquid-outlet` in `application.hbs`.

If you are okay with the dirty hacks that get this to work or you can fix up the code yourself, feel free to merge, but TBH I feel like I'm done spending time on this, so it's up to you :-)

### CODE REVIEW

**Comment by xtagon** [comment]
Some more notes:

- The layout itself could use some cleanup (vbox in a lot of places that could probably just be box, etc.)
- It doesn't have any special responsive attributes yet, but that could probably easily be added!

**Comment by rwwagner90** [comment]
@xtagon we're probably not okay with those hacks, but I'll take a look at your example and see if I can figure out what you were going for and get it to work 👍

**Comment by xtagon** [comment]
@rwwagner90 Thanks, sounds fair :-)

**Comment by rwwagner90** [comment]
I think this is what you were going for @xtagon https://github.com/html-next/flexi/pull/132

**Pull request closed without merging**
